# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - amdsharktank

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: "Unit Tests (${{ matrix.runs-on }}, ${{ matrix.python-version }}, ${{ matrix.torch-version }})"
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        torch-version: ["2.6.0"]
        runs-on: [ubuntu-24.04]
        include:
          - runs-on: windows-2022
            python-version: "3.12"
            torch-version: "2.6.0"
      fail-fast: false
    runs-on: ${{matrix.runs-on}}
    defaults:
      run:
        shell: bash
    env:
      PIP_CACHE_DIR: "${{ github.workspace }}/.pip-cache"
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{matrix.python-version}}

      - name: Cache Pip Packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: cache-pip
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('*requirements*.txt','amdsharktank/requirements*.txt') }}

      - name: Install pip deps
        run: |
          python -m pip install --no-compile --upgrade pip

          # Note: We install in three steps in order to satisfy requirements
          # from non default locations first.
          pip install --no-compile \
            --index-url https://download.pytorch.org/whl/cpu torch==${{matrix.torch-version}}+cpu
          pip install -r requirements-iree-pinned.txt
          pip install --no-compile \
            -r amdsharktank/requirements-tests.txt \
            -e amdsharktank/

          pip freeze

      - name: Run amdsharktank tests with coverage
        if: ${{ !cancelled() }}
        run: |
          pytest -n 20 amdsharktank/ \
            --cov=amdsharktank \
            --cov-report xml:cov.xml \
            --cov-config=.coveragerc \
            --durations=10 \
            --log-cli-level=info \
            -v
        env:
          COVERAGE_FILE: .coverage.${{ matrix.python-version }}.${{ matrix.torch-version }}.${{ matrix.runs-on }}

      - name: Upload coverage data
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        with:
          name: coverage-data-${{ matrix.python-version }}-${{ matrix.torch-version }}-${{ matrix.runs-on }}
          path: .coverage.${{ matrix.python-version }}.${{ matrix.torch-version }}.${{ matrix.runs-on }}
          include-hidden-files: true

      - name: Upload coverage to Codecov
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
        with:
          files: cov.xml

  coverage:
    name: Coverage
    runs-on: ubuntu-24.04
    needs: test
    if: github.event.pull_request.number != 2677  # Skip for large PR that exceeds GitHub's 300-file diff limit
    permissions:
      pull-requests: write
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        id: download
        with:
          pattern: coverage-*
          merge-multiple: true

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@e623398c19eb3853a5572d4a516e10b15b5cefbc # v3.39
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_COVERAGE_FILES: true
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 70

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt


  test-mi300x:
    name: "Unit Tests (${{ matrix.runs-on }}, ${{ matrix.python-version }}, ${{ matrix.torch-version }})"
    strategy:
      matrix:
        python-version: ["3.12"]
        torch-version: ["2.6.0"]
        iree-target-args: ["--iree-hip-target=gfx942 --iree-hal-target-device=hip"]
        runs-on: [linux-mi325-8gpu-ossci-nod-ai]
      fail-fast: false
    runs-on: ${{matrix.runs-on}}
    defaults:
      run:
        shell: bash
    env:
      PIP_CACHE_DIR: "${{ github.workspace }}/.pip-cache"
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{matrix.python-version}}

      - name: Cache Pip Packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: cache-pip
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('*requirements*.txt','amdsharktank/requirements*.txt') }}

      - name: Install pip deps
        run: |
          amdsharktank/build_tools/install_test_dependencies.sh \
            --torch-version ${{matrix.torch-version}} \
            --pytorch-rocm
          pip freeze

      - name: Run amdsharktank tests
        if: ${{ !cancelled() }}
        run: |
          pytest amdsharktank/ \
            --durations=10 \
            --capture=no \
            --log-cli-level=info \
            -v \
            --iree-hal-target-device=hip \
            --iree-hip-target=gfx942 \
            --iree-device=hip://0 \
            --device=cuda:0

  test_with_data:
    name: "Data-dependent Tests"
    strategy:
      matrix:
        python-version: [3.11]
        torch-version: ["2.6.0"]
        runs-on: [linux-mi325-1gpu-ossci-nod-ai]
      fail-fast: false
    runs-on: ${{matrix.runs-on}}
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
      HF_HOME: "/amdshark-cache/data/huggingface"
      HF_TOKEN: ${{ secrets.HF_FLUX_TOKEN }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{matrix.python-version}}

      - name: Create Python venv
        run: python -m venv ${VENV_DIR}

      - name: Install amdsharktank deps
        run: |
          source ${VENV_DIR}/bin/activate
          amdsharktank/build_tools/install_test_dependencies.sh \
            --torch-version ${{matrix.torch-version}} \
            --pytorch-rocm
          pip freeze

      - name: Run tests
      # TODO: unify with-*-data flags into a single flag and make it possible to run
      # only tests that require data.
      # We would still want the separate flags as we may endup with data being
      # scattered on different CI machines.
        run: |
          source ${VENV_DIR}/bin/activate
          pytest \
            -v \
            --log-cli-level=info \
            --with-quark-data \
            --iree-hal-target-device=hip \
            --iree-hip-target=gfx942 \
            --iree-device=hip://0 \
            amdsharktank/tests/models/llama/quark_parity_test.py \
            --durations=0 \
            --timeout=800

  test_integration:
    name: "Model Integration Tests"
    strategy:
      matrix:
        python-version: ["3.11"]
        torch-version: ["2.6.0"]
        runs-on: [ubuntu-24.04]
      fail-fast: false
    runs-on: ${{matrix.runs-on}}
    env:
      PIP_CACHE_DIR: "${{ github.workspace }}/.pip-cache"
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{matrix.python-version}}

      - name: Cache Pip Packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: cache-pip
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('*requirements*.txt','amdsharktank/requirements*.txt') }}

      - name: Install pip deps
        run: |
          amdsharktank/build_tools/install_test_dependencies.sh \
            --torch-version ${{matrix.torch-version}}
          pip freeze

      - name: Run punet fp16 tests
        run: |
          pytest -v amdsharktank/ -m punet_quick_fp16 \
            --durations=0 \
            --timeout=900

      - name: Run punet int8 tests
        run: |
          pytest -v amdsharktank/ -m punet_quick_int8 \
            --durations=0 \
            --timeout=900

  # Depends on other jobs to provide an aggregate job status.
  # TODO(#584): move test_with_data and test_integration to a pkgci integration test workflow?
  ci_sharktank_summary: # TODO: rename to ci_amdsharktank_summary
    if: always()
    runs-on: ubuntu-24.04
    needs:
      - test
    steps:
      - name: Getting failed jobs
        run: |
          echo '${{ toJson(needs) }}'
          FAILED_JOBS="$(echo '${{ toJson(needs) }}' \
            | jq --raw-output \
            'map_values(select(.result!="success" and .result!="skipped")) | keys | join(",")' \
          )"
          if [[ "${FAILED_JOBS}" != "" ]]; then
            echo "The following jobs failed: ${FAILED_JOBS}"
            exit 1
          fi
