# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - sharktuner

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/ci-sharktuner.yml'
      - 'sharktuner/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ci-sharktuner.yml'
      - 'sharktuner/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: "Unit Tests (py${{ matrix.python-version }}, ${{ matrix.runs-on }})"

    strategy:
      matrix:
        python-version: ["3.11"]
        runs-on: [ubuntu-24.04]
    runs-on: ${{matrix.runs-on}}
    defaults:
      run:
        shell: bash
    env:
      PIP_CACHE_DIR: "${{ github.workspace }}/.pip-cache"

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.python-version}}

      - name: Cache pip packages
        uses: actions/cache@v4
        id: cache-pip
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('sharktuner/requirements*.txt') }}

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r sharktuner/requirements-dev.txt

      - name: Install sharktuner dependencies
        run: |
          pip install -r sharktuner/requirements-iree.txt
          pip install -r sharktuner/requirements.txt
          pip install --no-compile \
            -r sharktuner/requirements-test.txt \
            -e sharktuner/
          pip freeze

      - name: Run mypy type checker
        run: mypy sharktuner --python-version ${{ matrix.python-version }}

      - name: Run sharktuner tests with coverage
        if: ${{ !cancelled() }}
        run: |
          pytest sharktuner/ \
            --cov=sharktuner \
            --cov-report xml:sharktuner-cov.xml \
            --cov-config=.coveragerc \
            -v
        env:
          COVERAGE_FILE: .coverage.sharktuner

      - name: Upload coverage data
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-sharktuner
          path: .coverage.sharktuner
          include-hidden-files: true

      - name: Upload sharktuner coverage to Codecov
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: codecov/codecov-action@v5
        with:
          files: sharktuner-cov.xml

  coverage:
    name: Coverage
    runs-on: ubuntu-24.04
    needs: test
    permissions:
      pull-requests: write
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        id: download
        with:
          name: coverage-data-sharktuner

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_COVERAGE_FILES: true
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 70

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
