# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Update IR for iree-test-suites

on:
  pull_request:
  workflow_dispatch:
  schedule:
    # Weekdays at 11:00 AM UTC = 03:00 AM PST / 04:00 AM PDT
    - cron: "0 11 * * 1-5"

permissions:
  contents: write
  pull-requests: write

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  upload_llama_iree:
    if: ${{ github.repository_owner == 'nod-ai' || github.event_name != 'schedule' }}
    timeout-minutes: 60
    name: "Update Llama 8B FP16 for IREE Test Suites"
    strategy:
      matrix:
        version: [3.11]
      fail-fast: false
    runs-on: linux-mi325-1gpu-ossci-nod-ai
    outputs:
      uploaded_new_ir: ${{ steps.upload-ir.outputs.uploaded_new_ir }}
      url_new_ir: ${{ steps.upload-ir.outputs.new_ir_url }}
      diff_lines_added: ${{ steps.upload-ir.outputs.diff_lines_added }}
      diff_lines_removed: ${{ steps.upload-ir.outputs.diff_lines_removed }}
    defaults:
      run:
        shell: bash
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Current Date
        id: date
        run: |
          echo "date=$(date -u +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - name: "Setting up Python"
        id: setup_python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{matrix.version}}
      - name: Create Python venv
        run: |
           echo "Date is ${date}"
           echo "Date stored is ${{ env.date }}"
           python -m venv ${VENV_DIR}
           source ${VENV_DIR}/bin/activate

      - name: Install pip deps
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          bash scripts/setenv.sh --nightly
          mkdir -p output_artifacts

      - name: Download weights and IR
        run: |
          wget https://sharkpublic.blob.core.windows.net/sharkpublic/halo-models/llm-dev/llama3_8b_random/real_weights.irpa
          wget https://raw.githubusercontent.com/iree-org/iree/refs/heads/main/tests/external/iree-test-suites/sharktank_models/quality_tests/llama/8b_f16_prefill_rocm.json
          jq '.mlir' 8b_f16_prefill_rocm.json | xargs wget -O old.mlir

      - name: Generate new IR
        run: |
          python3 -m sharktank.examples.export_paged_llm_v1  --irpa-file=real_weights.irpa \
            --output-mlir=output_artifacts/8b_f16_random-${{ env.date }}.mlir \
            --output-config=output_artifacts/8b_f16_random-${{ env.date }}.json \
            --bs-prefill=4 --bs-decode=4

      - name: Upload new IR
        id: upload-ir
        env:
          AZURE_SHARKPUBLIC_SAS_TOKEN: ${{ secrets.AZURE_SHARKPUBLIC_SAS_TOKEN }}
        run: |
          diff -q old.mlir output_artifacts/8b_f16_random-${{ env.date }}.mlir >& diff.txt || true
          echo diff_lines_added="$(diff old.mlir output_artifacts/8b_f16_random-${{ env.date }}.mlir  | grep "^>" | wc -l)" >> "${GITHUB_OUTPUT}"
          echo diff_lines_removed="$(diff old.mlir output_artifacts/8b_f16_random-${{ env.date }}.mlir  | grep "^<" | wc -l)" >> "${GITHUB_OUTPUT}"

          if  grep -q "differ" diff.txt ; then
            echo "IR has changed..upload new IR"
            az storage blob upload \
              --account-name sharkpublic \
              --sas-token "$AZURE_SHARKPUBLIC_SAS_TOKEN" \
              --container-name sharkpublic \
              --name halo-models/llm-dev/llama3_8b_random/8b_f16_random-${{ env.date }}.mlir \
              --file output_artifacts/8b_f16_random-${{ env.date }}.mlir \
              --overwrite
            echo uploaded_new_ir=true >> "${GITHUB_OUTPUT}"
            echo new_ir_url="https://sharkpublic.blob.core.windows.net/sharkpublic/halo-models/llm-dev/llama3_8b_random/8b_f16_random-${{ env.date }}.mlir" >> "${GITHUB_OUTPUT}"
          fi

      - name: Cleanup output artifacts
        run: |
            rm -rf output_artifacts
            rm -rf real_weights.irpa
            test ! -d output_artifacts && echo "Output artifacts are removed"

  create_iree_pr:
    name: "Create PR for IREE to update mlir location"
    needs: [ upload_llama_iree ]
    runs-on: ubuntu-24.04
    steps:
      - name: Get Current Date
        id: date
        run: |
          echo "date=$(date -u +'%Y-%m-%d')" >> "$GITHUB_ENV"

      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        if: ${{ env.CREATE_PULL_REQUEST_TOKEN_APP_ID != '' && env.CREATE_PULL_REQUEST_TOKEN_APP_PRIVATE_KEY != '' }}
        id: generate-token
        with:
          app-id: ${{ vars.IREE_FORK_APP_ID }}
          private-key: ${{ secrets.IREE_FORK_GITHUB_APP_PRIVATE_KEY }}
          owner: pravg-amd
          repositories: iree
        env:
          CREATE_PULL_REQUEST_TOKEN_APP_ID: ${{ vars.IREE_FORK_APP_ID }}
          CREATE_PULL_REQUEST_TOKEN_APP_PRIVATE_KEY: ${{ secrets.IREE_FORK_GITHUB_APP_PRIVATE_KEY }}

      - name: "Checkout IREE Repo"
        id: checkout_iree
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: iree
          ref: main
          token: ${{ steps.generate-token.outputs.token }}

      - name: "Make changes in IREE"
        if: ${{ needs.upload_llama_iree.outputs.uploaded_new_ir }}
        run: |
          new_url=${{ needs.upload_llama_iree.outputs.url_new_ir }}
          echo "Update mlir URL to $new_url"
          prefill_json="tests/external/iree-test-suites/sharktank_models/quality_tests/llama/8b_f16_prefill_rocm.json"
          decode_json="tests/external/iree-test-suites/sharktank_models/quality_tests/llama/8b_f16_decode_rocm.json"
          jq --arg updated_url "$new_url" '.mlir = $updated_url' $prefill_json > tmp.json && python -m json.tool tmp.json $prefill_json
          jq --arg updated_url "$new_url" '.mlir = $updated_url' $decode_json > tmp.json && python -m json.tool tmp.json $decode_json
          rm -rf tmp.json

      - name: "Create pull request"
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base: main
          author: iree-pr-automator[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: "update_llama_3.1_8b_${{ env.date }}"
          signoff: true
          title: "[iree-test-suites] Update llama 3.1 8B mlir source to ${{ env.date }}"
          body: |
            Update llama 3.1 8B mlir to the IR generated on ${{ env.date }}

            Diff info:
            Lines added: ${{ needs.upload_llama_iree.outputs.diff_lines_added }}
            Lines removed: ${{ needs.upload_llama_iree.outputs.diff_lines_removed }}

            Auto-generated by GitHub Actions using [`ci_iree_test_files.yml`](https://github.com/${{ github.repository }}/blob/main/.github/workflows/ci_iree_test_files.yml).
          commit-message: "Update llama 3.1 8B mlir source to ${{ env.date }}"
